//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSalary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class myPayrollEntities : DbContext
    {
        public myPayrollEntities()
            : base("name=myPayrollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<tblLogin> tblLogins { get; set; }
    
        public virtual ObjectResult<string> sp_CalculateIndividualSalary(Nullable<int> empId)
        {
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_CalculateIndividualSalary", empIdParameter);
        }
    
        public virtual int myproc(string c1, string c2, string c3)
        {
            var c1Parameter = c1 != null ?
                new ObjectParameter("C1", c1) :
                new ObjectParameter("C1", typeof(string));
    
            var c2Parameter = c2 != null ?
                new ObjectParameter("C2", c2) :
                new ObjectParameter("C2", typeof(string));
    
            var c3Parameter = c3 != null ?
                new ObjectParameter("C3", c3) :
                new ObjectParameter("C3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("myproc", c1Parameter, c2Parameter, c3Parameter);
        }
    
        public virtual ObjectResult<sp_TotalSalaries_Result> sp_TotalSalaries()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TotalSalaries_Result>("sp_TotalSalaries");
        }
    }
}
