//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSalary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogin
    {
        public short Login_ID { get; set; }
        public string Login_Name { get; set; }
        public string Login_Password { get; set; }
    }
}
